#
# See https://docs.microsoft.com/en-us/vsts/pipelines/yaml-schema for details
#

# Only run CI builds for these branches
trigger:
  branches:
    include:
    - 'master'
    - 'release/*'
# Run PR validation on all branches
pr:
  branches:
    include:
    - '*'

name: $(Date:yyMMdd)-$(Rev:rr)

jobs:
- template: build/templates/default-build.yml
  parameters:
    agentOs: Windows
    codeSign: true
    configuration: Release
    artifacts:
      publish: true
      path: 'artifacts/build/'

- template: build/templates/default-build.yml
  parameters:
    agentOs: macOS
    configuration: Release

- template: build/templates/default-build.yml
  parameters:
    agentOs: Linux
    configuration: Release

- job: Helix
  pool:
    name: Hosted VS2017
    vmImage: vs2017-win2016
  steps:
  - checkout: self
    clean: true
  - script: .\build.cmd -ci /t:Helix /p:Configuration=Debug
    displayName: Run build.cmd helix target

